name: Using strategy (Matrix)
on: push
jobs:
  node-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v

      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: 6

      - name: Log node version
        run: node -v
