name: Using strategy (Matrix)
on: push
jobs:
  node-versions:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_versions: [6, 8, 16]
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v

      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: ${{ matrix.node_versions }}

      - name: Log node version
        run: node -v
